Welcome page
agency-of-learning/PairApp pull request #237
Opened 2023-08-15 00:23 UTC by GALTdea

## What's the change?
Added Homepage (Hero, Testimonial,Problem) sections.

## Highlights / Surprises / Risks / Cleanup
Needed to add a couple of helpers to conditionally render navbars and style for the welcome page.

## Demo / Screenshots
![Screen Shot 2023-08-14 at 5 12 59 PM](https://github.com/agency-of-learning/PairApp/assets/16809030/4302fbc3-c910-49f7-a124-874309052889)
![Screen Shot 2023-08-14 at 5 13 15 PM](https://github.com/agency-of-learning/PairApp/assets/16809030/f8017fa5-c151-45b3-a911-636827ce6632)
![Screen Shot 2023-08-14 at 5 13 23 PM](https://github.com/agency-of-learning/PairApp/assets/16809030/4b258816-44ef-4ce8-9ac3-e46c39df9880)

Mobile:
![Screen Shot 2023-08-14 at 5 16 02 PM](https://github.com/agency-of-learning/PairApp/assets/16809030/1bd10425-a819-44fd-a288-eb19b94534e8)
![Screen Shot 2023-08-14 at 5 16 21 PM](https://github.com/agency-of-learning/PairApp/assets/16809030/a9db6c61-76ce-425b-8052-476656896141)
![Screen Shot 2023-08-14 at 5 16 32 PM](https://github.com/agency-of-learning/PairApp/assets/16809030/5b3b4e68-0fc
![Screen Shot 2023-08-14 at 5 16 40 PM](https://github.com/agency-of-learning/PairApp/assets/16809030/29168e4a-46a6-4ebc-ae48-e66df495c45e)
8-4a2b-b466-c6f2e8562a0d)

## Checklist before requesting a review

2023-08-15 02:10 UTC, JoshDevHub requested changes
Looks pretty good. I was also maybe wondering about the image sizing in the testimonials section, as that was discussed in the meeting today.

Not necessarily a blocker, but I also think it'd help some if this file broke some of its reusable sections out into partials or something. Would make the markup easier to reason about and would help maintain consistency. That can be done later though if there's no bandwidth to deal with it now.

2023-08-15 02:10 UTC, JoshDevHub commented on app/views/landing/index.html.erb
> +              <strong>Mastermind Community</strong>
So I realize this is how it is on the current main site, but it feels weird to me how on mobile, you get 2 paragraphs together, then two images.
![Selection_243](https://github.com/agency-of-learning/PairApp/assets/88392688/b144b931-d0ff-4e08-8ac7-eea04b26e271)
![Selection_244](https://github.com/agency-of-learning/PairApp/assets/88392688/16aa522f-082a-48a8-b0c6-bd79c91e2c0a)

You can fix this but still keep the staggered layout on desktop by changing `flex-col` to `flex-col-reverse` on line 174. And you'd want to do this same thing further down the page where this also occurs.

2023-08-15 02:42 UTC, toyhammered commented on app/views/landing/index.html.erb
> +              <svg xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 448 512">
Second to this, please make sure to use font awesome icons.

2023-08-15 17:59 UTC, GALTdea commented on app/views/landing/index.html.erb
> +              <svg xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 448 512">
I just changed all the svg's to font awesome classes but haven't had a chance to figure out how abstract out into a partial. I'll try to work on it today, but not sure I can get to it on time. If ready we can merge this and I can  submit a new PR for that

2023-08-16 04:58 UTC, JoshDevHub commented on app/views/landing/index.html.erb
> +              <svg xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 448 512">
I just wouldn't worry about it. We can bring it up in a new ticket later. Shipit :boat:

2023-08-16 05:00 UTC, JoshDevHub approved these changes
LGTM

2023-08-16 05:00 UTC, merged