416 usermenteeapplication 20admin move the cohorts indexshow pages under admin namespace
agency-of-learning/PairApp pull request #425
Opened 2023-11-09 21:19 UTC by Natblow

## What's the change?
With @Caleb-Mitchell we moved the cohort index/show into an admin interface.

## What key workflows are impacted?
Routes.
## Highlights / Surprises / Risks / Cleanup
We had to rename all the models/views/controllers into namespace, as well as in the Specs
## Demo / Screenshots
![image](https://github.com/agency-of-learning/PairApp/assets/85266997/79d307c3-0151-4b6f-8fbc-717db40bdee3)

## Issue ticket number and link
#416 

## Checklist before requesting a review

Please delete items that are not relevant.

- [X] Did you add appropriate automated tests?
- [X] Is everything elevated to the highest level? (e.g., can logic be moved out of view into controllers, or out of controllers into models?)
- [X] Is there any linting that needs to be executed?

2023-11-10 00:53 UTC, toyhammered requested changes
This seems mostly fine minus moving the model (which kinda cascades removing some of the changes you did).

I feel like this is also partially my fault for the lack of clarity, but generally you only need to scope your controllers, not the models (multiple controllers can talk to the same model)

2023-11-10 00:53 UTC, toyhammered commented on app/models/admin/user_mentee_application_cohort.rb
> +class Admin::UserMenteeApplicationCohort < ApplicationRecord
So we shouldn't be changing the model namespace. This should remain `UserMenteeApplicationCohort` still.

2023-11-10 20:57 UTC, Caleb-Mitchell commented
Great we corrected now. 

We encountered an issue on `app/views/admin/user_mentee_application_cohorts/_table_row` where we needed to update the path method. That's why we originally tried namespacing the model and it worked. 

But, actually we just need to write it like this `admin_user_mentee_application_cohort_path(cohort)` :smile: .

2023-11-11 01:02 UTC, toyhammered requested changes
Still a few more lingering `Admin::` that shouldn't be there.

2023-11-11 01:02 UTC, toyhammered commented on app/controllers/user_mentee_applications_controller.rb
> +    @active_cohort = Admin::UserMenteeApplicationCohort.active
This shouldn't be namespaced

2023-11-11 01:02 UTC, toyhammered commented on db/seeds.rb
> +  original_cohort = Admin::UserMenteeApplicationCohort.create!(
These shouldn't either be namespaced.

2023-11-11 01:02 UTC, toyhammered commented on lib/tasks/reapplication_notification_task.rake
> +  active_cohort = Admin::UserMenteeApplicationCohort.active
Also these

2023-11-11 01:02 UTC, toyhammered commented on spec/mailers/previews/mentee_application_mailer_preview.rb
> +      active_cohort_name: Admin::UserMenteeApplicationCohort.active.name).notify_applicant_to_reapply
and this

2023-11-11 17:55 UTC, Natblow commented
Thank you! Done now.

2023-11-11 18:08 UTC, toyhammered approved these changes

2023-11-11 18:09 UTC, merged